### ISSUE TITLE
Awesome library but elaborate how to add the data to realmMap

### ISSUE THREAD

**Issue by anvesh523** [thorbenprimke/realm-mapview#2]
<3

**Comment by anvesh523** [comment]
Can you please 'elaborate how to add the data' to map view(realmMap). Right now you are using 'com.github.thorbenprimke:realm-sfrestaurant-data:0.9.1'  for the data and businesses.csv file. 

Thanks for the library.

**Comment by jesusmartinoza** [comment]
Hi, have you been able to use custom data from Realm? I can't :/ It throws me
`java.lang.NoSuchMethodError: No virtual method getColumnType(J)Lio/realm/internal/ColumnType; in class Lio/realm/internal/Table; or its super classes (declaration of 'io.realm.internal.Table'`

**Comment by anvesh523** [comment]
No, I didn't get exactly how to use it. so, I didn't try

**Comment by vork** [comment]
You need to change the 

> getValue()

function in RealmClusterManager.

>  private double getValue(Row row, RealmFieldType columnType, long columnIndex) {
>     if (columnType == RealmFieldType.DOUBLE) {
>       return row.getDouble(columnIndex);
>     } else if (columnType == RealmFieldType.FLOAT) {
>       return row.getFloat(columnIndex);
>     } else if (columnType == RealmFieldType.INTEGER) {
>       return row.getLong(columnIndex);
>     }
>     throw new IllegalStateException("The value type needs to be of double, float or int");
>   }

ColumnType isn't used by realm anymore. It's RealmFieldType now.

**Edit:** I've created a pull request

**Comment by MiguelFale** [comment]
@vork I can't change .class files. How do I get to/override getValue?

**Comment by vork** [comment]
@MiguelFale Download source, apply my pull request, compile, include in project, use map.

**Comment by alfredmack** [comment]
Is there any other way to add data in realmap without modifying the library

**Comment by wzieba** [comment]
Yeah, I don't get it too. Isn't it 1st priority thing to add those elements to map that you want, not all of them? +1 edit: I think, it makes lib useless for 90% use cases... :(
