### ISSUE TITLE
Cluster styles

### ISSUE THREAD

**Issue by MiguelFale** [thorbenprimke/realm-mapview#6]
Is there an easy way to edit the cluster symbols?

Thanks!

**Comment by wrparrish** [comment]
Well yeah,  its fairly well documented in the library.

The class  RealmClusterRenderer  exposes a method called  'onBeforeClusterItemRendered()'
As its parameter it  provides access to a MarkerOptions object,   which can be used in the following manner:
https://developers.google.com/android/reference/com/google/android/gms/maps/model/MarkerOptions#inherited-constant-summary
