### ISSUE TITLE
1.0 support

### ISSUE THREAD

**Issue by wrparrish** [thorbenprimke/realm-mapview#8]
Given the recent 1.0 milestone being accomplished, this project would benefit from the future proofing of migrating to the latest version.

I think the need for maintenance would be greatly decreased with this stable release,  and it would also  helps make this more of a drop in implementation.   This library solves a major use case of an upcoming project at work,  and i'd love it to be a drop in solution.

**Comment by thorbenprimke** [comment]
hi @wrparrish. Totally agree - all my repos were a little behind during the sprint towards Realm 1.0. They are all updated now. 

You should be able to just drop it in now. The example is probably the easiest way to get started. If you have an enhancements or fixes, please send a PR.
